#GET
GET http://localhost:3000/
authorization: Basic TWFzdGVyczpBY2FkZW15

###
GET http://localhost:3000/task/filter?field=type&value=socks
authorization: Basic TWFzdGVyczpBY2FkZW15

###

GET http://localhost:3000/task/highest_price
authorization: Basic TWFzdGVyczpBY2FkZW15

###

GET http://localhost:3000/task/modify
authorization: Basic TWFzdGVyczpBY2FkZW15

###

GET http://localhost:3000/task/swap
authorization: Basic TWFzdGVyczpBY2FkZW15

###

GET http://localhost:3000/sales/sales_callbacks
authorization: Basic TWFzdGVyczpBY2FkZW15

###

GET http://localhost:3000/sales/sales_promise
authorization: Basic TWFzdGVyczpBY2FkZW15

###

GET http://localhost:3000/sales/sales_async
authorization: Basic TWFzdGVyczpBY2FkZW15

###

GET http://localhost:3000/asdasd
authorization: Basic TWFzdGVyczpBY2FkZW15

###

GET http://localhost:3000/products/get/14
authorization: Basic TWFzdGVyczpBY2FkZW15

###
#POST

POST Http://localhost:3000/task/rewrite
authorization: Basic TWFzdGVyczpBY2FkZW15
Content-Type: application/json

[
    {"type":"socks","color":"red","quantity":10,"priceForPair":"$3"},
    {"type":"socks","color":"green","priceForPair":"$10"},
    {"type":"hat","color":"blue","quantity":8,"price":"$6"}
]
###
#DELETE

DELETE Http://localhost:3000/products/delete/1

###