#GET
GET http://localhost:3000/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5ODI2ODIsImV4cCI6MTYwODk4MjY5N30.Ag_ElnH56KKG6ry4E_h2aweAnnu0Xl79U_fdc69dJxI

###
GET http://localhost:3000/task/filter?field=type&value=socks
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5ODI2ODIsImV4cCI6MTYwODk4MjY5N30.Ag_ElnH56KKG6ry4E_h2aweAnnu0Xl79U_fdc69dJxI

###

GET http://localhost:3000/task/highest_price
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5ODI2ODIsImV4cCI6MTYwODk4MjY5N30.Ag_ElnH56KKG6ry4E_h2aweAnnu0Xl79U_fdc69dJxI

###

GET http://localhost:3000/task/modify
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5ODI2ODIsImV4cCI6MTYwODk4MjY5N30.Ag_ElnH56KKG6ry4E_h2aweAnnu0Xl79U_fdc69dJxI

###

GET http://localhost:3000/task/swap
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5ODI2ODIsImV4cCI6MTYwODk4MjY5N30.Ag_ElnH56KKG6ry4E_h2aweAnnu0Xl79U_fdc69dJxI

###

GET http://localhost:3000/sales/sales_callbacks
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5ODI2ODIsImV4cCI6MTYwODk4MjY5N30.Ag_ElnH56KKG6ry4E_h2aweAnnu0Xl79U_fdc69dJxI

###

GET http://localhost:3000/sales/sales_promise
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5ODI2ODIsImV4cCI6MTYwODk4MjY5N30.Ag_ElnH56KKG6ry4E_h2aweAnnu0Xl79U_fdc69dJxI

###

GET http://localhost:3000/sales/sales_async
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5ODI2ODIsImV4cCI6MTYwODk4MjY5N30.Ag_ElnH56KKG6ry4E_h2aweAnnu0Xl79U_fdc69dJxI

###

GET http://localhost:3000/asdasd
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5ODI2ODIsImV4cCI6MTYwODk4MjY5N30.Ag_ElnH56KKG6ry4E_h2aweAnnu0Xl79U_fdc69dJxI

###

GET http://localhost:3000/products/get/b1c65c70-8eb-429e-b38b-b1a5b7f0c86e
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc3RlcnMiLCJwYXNzd29yZCI6IkFjYWRlbXkiLCJpYXQiOjE2MDg5ODU1NzYsImV4cCI6MTYwODk4NTYwNn0.HI3tHY-fmrIZ5D_ZROfpcbMSng2fk9Ax3OlLwKNiPAE
###

###

GET http://localhost:3000/orders/get/e3bbe26a-4065-4977-8b27-e70dc7e7b390
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc3RlcnMiLCJwYXNzd29yZCI6IkFjYWRlbXkiLCJpYXQiOjE2MDg5ODU1NzYsImV4cCI6MTYwODk4NTYwNn0.HI3tHY-fmrIZ5D_ZROfpcbMSng2fk9Ax3OlLwKNiPAE
###

GET http://localhost:3000/orders/get_delivery_price/e8588729-378e-4227-b758-3416ca3b2686
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc3RlcnMiLCJwYXNzd29yZCI6IkFjYWRlbXkiLCJpYXQiOjE2MDg5ODU1NzYsImV4cCI6MTYwODk4NTYwNn0.HI3tHY-fmrIZ5D_ZROfpcbMSng2fk9Ax3OlLwKNiPAE
###

GET http://localhost:3000/orders/cancel/1c66c636-0732-4187-aa2d-ddfc5f0bf69a
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc3RlcnMiLCJwYXNzd29yZCI6IkFjYWRlbXkiLCJpYXQiOjE2MDg5ODU1NzYsImV4cCI6MTYwODk4NTYwNn0.HI3tHY-fmrIZ5D_ZROfpcbMSng2fk9Ax3OlLwKNiPAE
###
#POST

POST http://localhost:3000/task/rewrite
authorization: Basic TWFzdGVyczpBY2FkZW15
Content-Type: application/json

[
    {"type":"socks","color":"red","quantity":10,"priceForPair":"$3"},
    {"type":"socks","color":"green","priceForPair":"$10"},
    {"type":"hat","color":"blue","quantity":8,"price":"$6"}
]

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "Masters",
    "password": "Academy" 
}

###
POST http://localhost:3000/orders/add_product
Content-Type: application/json

{
    "productId": "ef95a974-b3f7-47c4-82a2-1c06fc6da3a3",
    "quantity": 20
}

###

POST http://localhost:3000/orders/change_status
Content-Type: application/json

{
    "orderId": "fccff04e-b28e-48af-8aec-938e4ba60632",
    "status": "Opened"
}

###
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc3RlcnMiLCJwYXNzd29yZCI6IkFjYWRlbXkiLCJpYXQiOjE2MDg5ODU1MzR9.eOqwj0v6-1N_UE-eSVm38AzQop55hGkSbaWFHxCHuTU"
}

###
POST http://localhost:3000/orders/set_route
Content-Type: application/json

{
    "id": "e8588729-378e-4227-b758-3416ca3b2686",
    "addresses": {
        "from": "Черкаси",
        "to": "Львів"
    }
}

###
#DELETE

DELETE Http://localhost:3000/products/delete/23
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg5ODI2ODIsImV4cCI6MTYwODk4MjY5N30.Ag_ElnH56KKG6ry4E_h2aweAnnu0Xl79U_fdc69dJxI

Content-Type: application/json
###